### PR TITLE
Fix travis build [WIP]

### PR DESCRIPTION
**Pull request by abinoam**
@Ptico  Don't merge it yet. Opening it so you can see what I have already done.
I may do some rebasing still. 👍

### CODE REVIEW

**Comment by abinoam** [comment]
I'll have to do some forth and back here.
I've just discovered that we're locked at specific ruby patch level versions because of `parser` a `mutant` dependency.
When I get to a "final" form, I'll rebase.

See: 
```
warning: parser/current is loading parser/ruby21, which recognizes

warning: 2.1.8-compliant syntax, but you are running 2.1.10.

warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

**Comment by Ptico** [comment]
I personally don't care about rebasing, so it's up to you. Let's lock the 2.1.8 and then reorganize, simplify and update development tools. Possibly we can bundle devtools and run mutant separately somehow

**Comment by abinoam** [comment]
Locking the patching versions at travis and:

2.1.8 -> not running mutant tests
2.2.6 -> running
2.3.3 -> running
2.4.0 -> running

They're running but not passing mutation tests (not yet).
My plan, run mutation tests in just ONE in a separate item of travis matrix.
Put it in allow_failures.

**Comment by abinoam** [comment]
With these last commits we are officially green. Although mutation tests are red.

**Comment by abinoam** [comment]
I think I'll not rebase. Later someone can track some of the reasoning behind the current travis configuration.

@Ptico After travis finish, feel free to merge, modify, whatever!

I'll have to take a break now. Perhaps I'll not be back today, only tomorrow.

**Comment by abinoam** [comment]
One more commit. Rubocop didn't like the caching of gems at vendor/ folder.

**Comment by abinoam** [comment]
arewegreen

**Comment by Ptico** [comment]
finally

**Comment by mbj** [comment]
> With these last commits we are officially green. Although mutation tests are red.

If you have any questions on mutation testing, feel free to show up in my slack channel.

**Comment by abinoam** [comment]
@mbj I'll surely will. These mutation tests are so cool!

**Comment by mbj** [comment]
@abinoam I'm searching participants for a public mutant code dive, so I can point to it in the future. Are you interested? https://twitter.com/_m_b_j_/status/926277814600466433 //cc everyone here.

**Comment by abinoam** [comment]
I'm not good at english so I'm not finding the words to explain my situation to you.
My actual work, the one that pays my bills, happens most of the time without being scheduled (<- don't know the word for this). But, I just wait for being requested, then I go out almost immediately.
So I have a poor schedule. I'm afraid to being recorded and suddenly I gotta go out and leave you alone. But, if there's more people involved and there's no problem if I go out and come in later when you're recording, perhaps I can participate. And I would surely enjoy it!

**Pull request merged**
