### PR TITLE
Resolves #16 - Update flexus.gemspec and bundler related things (REOPENED)

### LINKED ISSUE #16: Bring flexus to the current bundler standard for gemspec
See if `flexus.gemspec` needs any improvement

### PR DESCRIPTION
**Pull request by abinoam**
I need your e-mail to put at the `flexus.gemspec` @Ptico 
I bumped up version to 1.0.0 as I'm considering renaming Inflecto module to Flexus module is an api breaking change.
Other things on this PR:
* Remove spec.test_files as its use is deprecated.
* Don't bundle test files with the gem.
* Remove .rvmrc as bundle do all the work and we don't need gemsets anymore (for our use case).
* Added bundler rake tasks, so we can later do `rake release`

This is the same PR #17. reopened it because I have deleted my repo.

### CODE REVIEW

**Comment by abinoam** [comment]
Now my repo is a fork of @Ptico's fork.

captura de tela 2017-11-03 as 01 43 14

**Comment by Ptico** [comment]
Let's go with 1.0 and then start 2.0dev. My email is: andrey@aejis.eu

**Review by Ptico — APPROVED** [review]

**Comment by Ptico** [comment]
I forgot to mention that we need to update "Migration from inflecto" section in readme with new versions

**Comment by abinoam** [comment]
Doing it now!

**Comment by Ptico** [comment]
👍

**Comment by Ptico** [comment]
https://rubygems.org/gems/flexus – 🎉

**Comment by abinoam** [comment]
🎉🎉🎉

**Comment by abinoam** [comment]
@Ptico,

You have to setup codeclimate, coverwalls and gemnasium.
With this PR all badges are already pointing to the default urls of theses services.
You just need to setup the hooks.

**Comment by Ptico** [comment]
Working on this

**Pull request merged**
