### PR TITLE
Update README.md about Dry::Inflector merge

### PR DESCRIPTION
**Pull request by abinoam**
See: #22

### CODE REVIEW

**Comment by abinoam** [comment]
@jodosha @Ptico @solnic @mbj do you approve this README?

**Comment by mbj** [comment]
Does this mean I can nuke `mbj/inflector` down to a "please look at `dryrb/dry-inflector`" ?

**Comment by abinoam** [comment]
I think so!
But, perhaps you can wait some time until we get dry-inflector released at least.
It's only at github.
No rubygems yet.

https://rubygems.org/search?utf8=%E2%9C%93&query=dry-inflector

**Review by jodosha — APPROVED** [review]
LGTM 👍

**Comment by jodosha** [comment]
@abinoam @Ptico @mbj Does Flexus have more features than `inflecto`/`dry-inflector`? I'd like if we can wrap a `v0.1.0` ASAP. 👍

**Comment by jodosha** [comment]
@Ptico @abinoam Quick update: in the meantime, I cleaned up the `dry-inflector` code, and added both of you as committers over there. Please remember yourselves to the `.gemspec` file.

IMO the gem is ready for a `v0.1.0` release over Rubygems, unless you need/want to port code from here to there.

**Comment by Ptico** [comment]
@jodosha v1.0.0.beta.1 branch contains only small fixes and mbj/inflecto#8 performance improvements and 100% compatible with inflecto 0.0.2 so I think it can be published

**Comment by jodosha** [comment]
@Ptico Please implement it in `dry-inflector`. Thanks!

**Comment by mbj** [comment]
> I think so!
> But, perhaps you can wait some time until we get dry-inflector released at least.
> It's only at github.
> No rubygems yet.

Okay, please ping me at the original repo once its ready to be nuked.

**Pull request merged**
